name: Publish Package

on:
  workflow_dispatch:
  release:
    types: [created]

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - uses: actions/setup-node@v6
        name: Pull in Node
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org/
      - run: npm install
        name: Install Packages
      - run: npm run package
        name: Package
      - run: npm publish --access public -q
        name: Publish
